package utilities;

public class AndroidLocators {
	public static final String productsLabel = "accessibility id;container header";
	public static final String menuIcon = "accessibility id;open menu";
	public static final String allMenuItems = "xpath;//android.view.ViewGroup[contains(@content-desc,'menu item')]/android.widget.TextView";
	public static final String allProducts = "accessibility id;store item";
	public static final String catalogMenu = "accessibility id;menu item catalog";
	public static final String webviewMenu = "accessibility id;menu item webview";
	public static final String drawingMenu = "accessibility id;menu item drawing";
	public static final String clearDrawingButton = "accessibility id;Clear button";
	public static final String saveDrawingButton = "accessibility id;Save button";
	public static final String signaturePad = "xpath;//android.view.View[@resource-id='signature-pad']";
	public static final String productsNames = "accessibility id;store item text";
	public static final String productsPrices = "accessibility id;store item price";
	public static final String productsImages = "class;android.widget.ImageView";
	public static final String storeButton = "accessibility id;sort button";
	public static final String cartBadge = "accessibility id;cart badge";
	public static final String sortButton = "accessibility id;sort button";
	public static final String sortNameAsc = "accessibility id;nameAsc";
	public static final String sortNameDesc = "accessibility id;nameDesc";
	public static final String sortPriceAsc = "accessibility id;pricAsc";
	public static final String sortPriceDesc = "accessibility id;priceDesc";
	public static final String itemsInCart = "xpath;//android.view.ViewGroup[@content-desc='cart badge']/android.widget.TextView";
	public static final String productName = "accessibility id;container header";
	public static final String counterMinusButton = "accessibility id;counter minus button";
	public static final String counterPlusButton = "accessibility id;counter plus button";
	public static final String counterAmount = "xpath;//android.view.ViewGroup[@content-desc=\"counter amount\"]/android.widget.TextView";
	public static final String addToCartButton = "accessibility id;Add To Cart button";
	public static final String productLabel = "accessibility id;product label";
	public static final String productPrice = "accessibility id;product price";
	public static final String totalItemNum = "accessibility id;total number";
	public static final String totalPrice = "accessibility id;total price";
	public static final String checkoutButton = "accessibility id;Proceed To Checkout button";
	public static final String usernameTextbox = "accessibility id;Username input field";
	public static final String passwordTextbox = "accessibility id;Password input fieldr";
	public static final String loginButton = "accessibility id;Login button";
	public static final String usernameErrorMessage = "accessibility id;Username-error-message";
	public static final String passwordErrorMessage = "accessibility id;Password-error-message";
	public static final String genericErrorMessage = "accessibility id;generic-error-message";
	public static final String removeProductFromCart = "xpath;(//android.view.ViewGroup[@content-desc='remove item'])[%d]";
	public static final String incProductInCart = "xpath;(//android.view.ViewGroup[@content-desc='counter plus button'])[%d]";
	public static final String decProductInCart = "xpath;(//android.view.ViewGroup[@content-desc='counter minus button'])[%d]";
	public static final String productAmountInCart = "xpath;(//android.view.ViewGroup[@content-desc='counter amount'])[%d]";
	public static final String nameCheckoutTextbox = "accessibility id;Full Name* input field";
	public static final String addressLine1Textbox = "accessibility id;Address Line 1* input field";
	public static final String addressLine2Textbox = "accessibility id;Address Line 2 input field";
	public static final String cityTextbox = "accessibility id;City* input field";
	public static final String stateTextbox = "accessibility id;State/Region input field";
	public static final String zipCodeTextbox = "accessibility id;Zip Code* input field";
	public static final String countryTextbox = "accessibility id;Country* input field";
	public static final String nameCheckoutError = "accessibility id;Full Name*-error-message";
	public static final String addressLine1Error = "accessibility id;Address Line 1*-error-message";
	public static final String addressLine2Error = "accessibility id;Address Line 2-error-message";
	public static final String cityTextError = "accessibility id;City*-error-message";
	public static final String stateTextError = "accessibility id;State/Region-error-message";
	public static final String zipCodeError = "accessibility id;Zip Code*-error-message";
	public static final String countryError = "accessibility id;Country*-error-message";
	public static final String toPaymentButton = "accessibility id;To Payment button";
	public static final String cardNumTextbox = "accessibility id;Card Number* input field";
	public static final String expDateTextbox = "accessibility id;Expiration Date* input field";
	public static final String securityCodeTextbox = "accessibility id;Security Code* input field";
	public static final String cardNumError = "accessibility id;Card Number*-error-message";
	public static final String expDateError = "accessibility id;Expiration Date*-error-message";
	public static final String securityCodeError = "accessibility id;Security Code*-error-message";
	public static final String sameAddressCheckbox = "accessibility id;checkbox for My billing address is the same as my shipping address.";
	public static final String reviewOrderButton = "accessibility id;Review Order button";
	public static final String deliveryAddress = "xpath;//android.view.ViewGroup[@content-desc='checkout payment info']/android.widget.TextView";
	public static final String billingAddress = "xpath;//android.view.ViewGroup[@content-desc='checkout billing address']/android.widget.TextView";
	public static final String deliveryDetails = "xpath;//android.view.ViewGroup[@content-desc='checkout delivery details']/android.widget.TextView";
	public static final String paymentMethodDetails = "xpath;//android.view.ViewGroup[@content-desc='checkout payment info']/android.widget.TextView";
	public static final String placeOrderButton = "accessibility id;Place Order button";
	public static final String checoutCompleteMessage = "xpath;//android.view.ViewGroup[@content-desc='checkout complete screen']/android.widget.ScrollView/android.view.ViewGroup/android.widget.TextView[1]";
	public static final String continueShoppingButton = "accessibility id;Continue Shopping button";
	public static final String grantPermission = "id;com.android.permissioncontroller:id/grant_dialog";
	public static final String savedMessageOKButton = "id;android:id/button1";
	public static final String lastElement = "xpath;//android.view.ViewGroup[@content-desc=\"products screen\"]/android.widget.ScrollView/android.view.ViewGroup/android.view.ViewGroup[4]";
	public static final String produtLa4bfe1 = "accessibility id;container header";
	public static final String prodcsLaf4bel = "accessibility id;container header";
	public static final String prouctsLaf4bel = "accessibility id;container header";
	
	
}
